version: 1.4

prefs:
  runLog:
    type: memory
    maxLen: 500

resultSinks:
- &stdoutSink
  type: stdout
  data: [stdout, stderr]

jobs:
  LongSync:
    cmd: "php /var/azuracast/www/util/cli.php sync:run long"
    time: "0 0 * * * *"
    notifyOnSuccess: [*stdoutSink]
    notifyOnError: [*stdoutSink]

  MediumSync:
    cmd: "php /var/azuracast/www/util/cli.php sync:run medium"
    time: "0 */5 * * * *"
    notifyOnSuccess: [*stdoutSink]
    notifyOnError: [*stdoutSink]

  QueueWorker:
    cmd: "php /var/azuracast/www/util/cli.php queue:process 275"
    time: "0 */5 * * * *"
    notifyOnSuccess: [*stdoutSink]
    notifyOnError: [*stdoutSink]

  ShortSync:
    cmd: "php /var/azuracast/www/util/cli.php sync:run short"
    time: "0 * * * * *"
    notifyOnSuccess: [*stdoutSink]
    notifyOnError: [*stdoutSink]

  NowPlayingSync:
    cmd: "php /var/azuracast/www/util/cli.php sync:run nowplaying"
    time: "*/15 * * * * *"
    notifyOnSuccess: [*stdoutSink]
    notifyOnError: [*stdoutSink]