#!/usr/bin/env bash

cd /var/azuracast/www

APPLICATION_ENV="${APPLICATION_ENV:-production}"

echo "Updating AzuraCast (Environment: $APPLICATION_ENV)"

if [ $APPLICATION_ENV = "production" ]; then
    git reset --hard && git pull
fi

# Install ansible
sudo add-apt-repository -y ppa:ansible/ansible
sudo apt-get update 
sudo apt-get install -q -y --no-install-recommends python2.7 python-setuptools python-wheel python-mysqldb ansible

sudo ansible-playbook util/ansible/docker_install.yml --inventory=util/ansible/hosts --extra-vars "app_env=$APPLICATION_ENV"