#!/usr/bin/env bash

cd /var/azuracast/www

APPLICATION_ENV="${APPLICATION_ENV:-production}"

echo "Updating AzuraCast (Environment: $APPLICATION_ENV)"

if [ $APPLICATION_ENV = "production" ]; then
    git reset --hard && git pull
    composer install --no-dev
else
    composer install
fi

php util/cli.php cache:clear

rm -rf /var/azuracast/www_tmp/*

php util/cli.php migrations:migrate --no-interaction --allow-no-migration

php util/cli.php orm:generate-proxies

php util/cli.php azuracast:radio:restart