#!/usr/bin/env bash

cd /var/azuracast/www

APPLICATION_ENV="${APPLICATION_ENV:-production}"

echo "Updating AzuraCast (Environment: $APPLICATION_ENV)"

if [ $APPLICATION_ENV = "production" ]; then
    git reset --hard && git pull
    composer install --no-dev
else
    if [ $APPLICATION_ENV = "testing" ]; then
        sudo mkdir -p vendor
        sudo chmod -R 0744 vendor
        sudo chown -R azuracast:azuracast vendor
    fi
    composer install
fi

azuracast_cli azuracast:setup:influx
azuracast_cli cache:clear
azuracast_cli migrations:migrate --no-interaction --allow-no-migration

if [ $APPLICATION_ENV = "development" ]; then
    azuracast_cli azuracast:setup:fixtures
fi

azuracast_cli cache:clear
azuracast_cli azuracast:radio:restart