#!/usr/bin/env bash

cd /var/azuracast/www

APPLICATION_ENV="${APPLICATION_ENV:-production}"

echo "Installing AzuraCast (Environment: $APPLICATION_ENV)"

if [ $APPLICATION_ENV = "production" ]; then
    rm -rf ./{*,.*}
    wget https://github.com/AzuraCast/AzuraCast/archive/master.tar.gz
    tar -xzvf master.tar.gz --strip-components 1
    rm master.tar.gz
    composer install -o --no-dev
else
    if [ $APPLICATION_ENV = "testing" ]; then
        sudo mkdir -p vendor
        sudo chmod -R 0744 vendor
        sudo chown -R azuracast:azuracast vendor
    fi
    composer install
fi

azuracast_cli azuracast:setup $*