#!/usr/bin/env bash

cd /var/azuracast/www

APPLICATION_ENV="${APPLICATION_ENV:-production}"

echo "Updating AzuraCast (Environment: $APPLICATION_ENV)"

if [ $APPLICATION_ENV = "production" ]; then
    find -maxdepth 1 ! -name plugins ! -name . -exec rm -rv {} \;
    wget https://github.com/AzuraCast/AzuraCast/archive/master.tar.gz
    tar -xzvf master.tar.gz --strip-components 1
    rm master.tar.gz
    composer install -o --no-dev
else
    composer install
fi

php util/cli.php azuracast:setup --update $*